function ScoreNormalization (new,LAN,bb);
dos(['ComputeNorm.exe --config ComputeNorm-HTK.cfg',...
    ' --tnormNistFile ', new,'\TestResults\'    ,LAN,'-',num2str(bb),'.res',...
    ' --testNistFile ' , new,'\TestResults\'    ,LAN,'-',num2str(bb),'.res',...
    ' --outputFile '   , new,'\NormTestResults\Norm_',LAN,'-',num2str(bb),'.res']);